config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
   resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show

    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        current_user.update(user_params)
        redirect_to current_user
      end
      

    private
    def user_params
        params.require(:user).permit(:username, :name, :website,
                               :bio, :email, :phone, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Framous</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="#">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Framus
          </a>
        </div>
        <div class="m-auto">
          <form class="form-inline search-form">
            <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
          </form>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          <% if user_signed_in? %>
          <a href="<%= user_path(current_user)%>">
            <i class="fa fa-user"></i>
          </a>
          <% else %>
          <a href="<%= new_user_session_path%>">
            <i class="fa fa-sign-in"></i>
          </a>
          <% end %>
          <% if user_signed_in? %>
          <a href="<%= destroy_user_session_path%>" data-method="delete">
            <% if user_signed_in? %>
          <a href="<%= destroy_user_session_path%>" data-method="delete">
            <i class="fa fa-sign-out"></i>
          </a>
        <% else %>
          <a href="<%= new_user_session_path%>">
            <i class="fa fa-sign-in"></i>
          </a>
        <% end %>
          </a>
        <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2022 FRAMUS </p>
      </nav>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
  <div class="form-group row">
    <div class="col-sm-3 col-form-label">
      <img class="avatar" src="https://scontent.fbrs4-2.fna.fbcdn.net/v/t39.30808-6/269938136_4732288780223960_2004795302643008557_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=174925&_nc_ohc=sE3p60Tcw7QAX_e8G1B&_nc_ht=scontent.fbrs4-2.fna&oh=00_AT9rZH2HCthoIoSr5XqRIctLjD_dKKaH1InsbmdZ7vLCBQ&oe=620F47A7">
    </div>
    <div class="col-sm-9">
      <p class="username"><%=current_user.username %></p>
      <a class="change-photo" href="">Change Profile Photo</a>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :username, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :username, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :website, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :website, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_area :bio, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :gender, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-9">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <img src="https://scontent.fbrs4-2.fna.fbcdn.net/v/t39.30808-6/269938136_4732288780223960_2004795302643008557_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=174925&_nc_ohc=sE3p60Tcw7QAX_e8G1B&_nc_ht=scontent.fbrs4-2.fna&oh=00_AT9rZH2HCthoIoSr5XqRIctLjD_dKKaH1InsbmdZ7vLCBQ&oe=620F47A7">
      </div>
    </div>
    
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= current_user.username %></h2>
              
        <a class="edit-profile" href="<%= edit_user_path(current_user) %>">
            <button>Edit Profile</button>
        </a>
      </div>
      <h2 class="bio"><%= current_user.bio %></h2> 
      <ul class="posts">
        <li><span>120</span> posts</li>
        <li><span>195 million</span> followers</li>
        <li><span>34</span> following</li>
      </ul>
      <h2 class="name"><%= current_user.name %></h2>
       <%=link_to current_user.website, current_user.website, class:  'website' %>
    </div>
  </div>
</div>
<div class="user-tabs">
  <a class="tab active" href="">
    <i class="fa fa-th"></i>
    POSTS
  </a>
  <a class="tab" href="">
    <i class="fa fa-tv"></i>
    IGTV
  </a>
  <a class="tab" href="">
    <i class="fa fa-bookmark"></i>
    SAVED
  </a>
  <a class="tab" href="">
    <i class="fa fa-tag"></i>
    TAGGED
  </a>
</div>
<div class="user-images">
  <div class="wrapper">
    <img src="https://scontent.fbrs4-1.fna.fbcdn.net/v/t1.6435-9/79773803_2717962274989964_7475430517588885504_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=174925&_nc_ohc=YGZ9vSDhgUQAX-vMEMD&_nc_ht=scontent.fbrs4-1.fna&oh=00_AT80-NC7FL5coH-iLFsmy6Dq8LyRNoXhRyYuepHnpEkeUg&oe=622D9BAD">
  </div>
  <div class="wrapper">
    <img src="https://scontent.fbrs4-1.fna.fbcdn.net/v/t1.6435-9/60454435_2328357827283746_8716384064191332352_n.jpg?_nc_cat=100&ccb=1-5&_nc_sid=174925&_nc_ohc=2dl5-o76A9QAX89CwKP&_nc_ht=scontent.fbrs4-1.fna&oh=00_AT8Yv3vnvQ-7_6vfLRUtVZ0eCpaMjtuz0VYzgwGsVwL1MA&oe=622EE510">
  </div>
  <div class="wrapper">
    <img src="https://scontent.fbrs4-1.fna.fbcdn.net/v/t1.6435-9/181472138_4013017742151071_3444251418493599592_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=PZu3EBewTIoAX_hUjca&_nc_ht=scontent.fbrs4-1.fna&oh=00_AT98ts23hj7eY9ZcsANi0ATadoFq-bgYiE0wS1Zcg5Gu_w&oe=622FD08B">
  </div>
</div>